#!/bin/bash

# compile light .jar of ORF.scala
# usage: ./lightScalaCompile

rm -rf classes
mkdir classes
scalac -d classes ../sbt/src/main/scala/ORF.scala
cd classes
jar cf orf.jar *
mv orf.jar ../
cd ../
rm -rf classes
